# -*- coding: utf-8 -*-
"""HOME PRACTICE.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15FSE56a_W5yWcz6y27GVmaw9HfHYwS_H

HOME PRACTICE
"""

_a = 5
print(_a)

message = "hello world"
print(message)

name ="wellcome"
print(name)

name ="thank you"
print(name)

name ="thank you sir"
print(name.title())

name = "sharafat khan"
print(name.upper())

name = "SHARAFAT KHAN"
print(name.lower())

First_Name = "sharafat"
Last_Name ="khan"
Full_Name = First_Name + " " +Last_Name
message ="wellcome " + Full_Name.title() + "."
print(message)

